default: &default
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: mysql2
  host: localhost
  username: root
  password: "123456"
  database: balad_development

test:
  <<: *default
  adapter: sqlite3
  database: db/balad_test.sqlite3

production:
  <<: *default
  adapter: mysql2
  host: localhost
  username: root
  password: "123456"
  database: balad_production
